name: Create Release

on:
    workflow_dispatch:
        inputs:
            version:
                description: 'rc or stable?'
                required: true
jobs:
    linting:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
            - name: Install dependencies
              run: npm ci
            - name: Build ZIP
              run: npm run package-plugin
              env:
                  CI: true
