name: E2E Tests

on:
    pull_request:
    push:
        branches:
            - trunk
jobs:
    e2e:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, start env and run e2e tests
        run: |
          npm ci
					npm run build:all
          npm run env:start
          npm run test:e2e
        env:
          CI: true
